name: Build Scheduler - prd

on:
  push:
    branches: [main]

jobs:
  build:
    uses: team-monolith-product/tmn-gh-actions/.github/workflows/build_v2.yml@main
    with:
      env: prd
      target: main
      helmRepository: jce-jupyter-hub-helm
      dockerTarget: runtime
      buildArgs: |
        ARCH=amd64
      propertyPath: 'jupyterhub-1.scheduling.userScheduler.image.tag'
      updateTargets: |
        {
          "aws": {
            "imageName": "tmn-ecr-k8s-scheduler",
            "valueFilePath": ["aws-apne2-prd-jupyter.yaml", "aws-euw2-prd-jupyter.yaml", "aws-mes1-prd-jupyter.yaml"]
          }
        }
    secrets:
      MACHINE_TOKEN: ${{ secrets.MACHINE_TOKEN }}
